parameters:
    hackzilla_ticket.user_load.class: Hackzilla\Bundle\TicketBundle\EventListener\UserLoad
    hackzilla_ticket.twig_user.class: Hackzilla\Bundle\TicketBundle\Extension\UserExtension
    hackzilla_ticket.ticket_manager.class: Hackzilla\Bundle\TicketBundle\Manager\TicketManager
    hackzilla_ticket.user_bridge.class: Hackzilla\Bundle\TicketBundle\User\FOSUser
    hackzilla_ticket.component.twig_extension.ticket_global.class: Hackzilla\Bundle\TicketBundle\Component\TwigExtension\TicketGlobalExtension

services:
    hackzilla_ticket.listener:
        class: %hackzilla_ticket.user_load.class%
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hackzilla_ticket_user_extension:
        class: %hackzilla_ticket.twig_user.class%
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    hackzilla_ticket.user:
        class: %hackzilla_ticket.user_bridge.class%
        arguments: ['@security.context', '@fos_user.user_manager']

    hackzilla_ticket.ticket_manager:
        class: %hackzilla_ticket.ticket_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]

    hackzilla_ticket.component.twig_extension.ticket_global:
        class: %hackzilla_ticket.component.twig_extension.ticket_global.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
